<div class ="background__wrapper">
    <div class ="background__image about__background__image"></div>
    <div class ="background__text">
        <p class ="first__header__text">Un chef passionné,</p>
        <p class ="second__header__text">riche d'un long parcours</p>   
    </div>
</div>

<div class ="introduction about__introduction">
    <!--<h1 class ="big__title"><span class ="satisfy">Un chef passionné</span> riche d'un long parcours</h1>-->
    <p>
        Riche de <?= date("Y") - 2010?> années d'expériences diverses en cuisine, Mehdi Baileche est un chef au parcours atypique. 
    </p>
    <p>Formé auprès de l'excellence de la cuisine française et ayant évolué dans différents types de restauration en France ou dans la région du Pacifique, il a su mettre à profit ses compétences acquises pour devenir un chef passionné, généreux et authentique.
    </p>
</div>
<div class ="about__global__wrapper">
    <div class="chief__photo">
        <img src="./medias/images/ChefMehdiPhoto.jpg" alt="photoChef">
    </div>
    <section class ="about__text__wrapper">
        <h2 class = "section__title">Les bases de la cuisine française</h2>
        <p>
        Très gourmand étant jeune, je ne n’étais pas destiné à être cuisinier mais scientifique. Ma passion
        pour la cuisine me pousse à me diriger à l&#39;âge de 23 ans vers ce magnifique métier. J’intègre alors en
        tant qu’apprenti la brigade du célèbre Jardin des Sens, le restaurant étoilé des frères Pourcels à
        Montpellier. Excellence, rigueur et travail sont les maitres mots de ce haut lieu de la gastronomie.
        J’obtiens ensuite mon Brevet Professionnel de cuisine et fais mes armes à la Maison de la Lozère. Ce
        mythique restaurant gastronomique montpellierain dirigé par le chef Eric Cellier et cité maintes fois
        dans le guide Gault et Millau, propose une cuisine audacieuse, raffinée mettant à l’honneur les
        produits languedociens. Je gagne en compétences et y apprends de belles valeurs en cuisine comme
        l’esprit d’équipe, le respect, la générosité et la régularité.  
        </p>
        <p>
        Je pars ensuite en région parisienne au Tastevin à Maisons-Laffitte, travailler au restaurant
        gastronomique du Chef Denis Rivoire, maison reconnue par les guides depuis de nombreuses
        années. La cuisine du chef est caractérisée par des ingrédients de luxe sublimés dans le respect des traditions culinaires françaises. En tant que chef de partie au poisson, j'ai été amené à travailler rigoureusement
        ces merveilleux produits.
        </p>
    </section> 
</div>
<div class ="about__global__wrapper" id="about__center__section">
    <div class="chief__photo">
        <img src="./medias/images/chefEnAction/4.jpg" alt="photoChef">
    </div>
    <section class ="about__text__wrapper">
        <h2 class = "section__title">La découverte de nouveaux horizons culinaires</h2>
        <p>Fort de mon expérience gastronomique française, je pars ensuite travailler à Sydney en Australie. Je
        suis recruté par le plus grand traiteur de la ville, European Catering Company, où j’y apprends un
        tout autre métier tant sur le plan de l’organisation que sur la production. Les prestations extérieures
        diverses et variées renforcent mon expérience professionnelle et m’amènent à travailler avec des
        personnes du monde entier. Je travaille en parallèle en tant que chef privé pour la société Chefin, où
        je réalise des diners raffinés pour des particuliers. Je développe mon esprit créatif, propose des
        menus en fonction des produits du marché et fait découvrir ainsi aux clients mon univers culinaire.
        C’est la révélation, je prends beaucoup de plaisir à être au contact direct des convives.
        </p>
        <p>
        Je pose ensuite mes valises en Nouvelle-Zélande et occupe le poste de Sous-Chef au restaurant
        vignoble Cable Bay Dining Room sur Waiheke Island, un magnifique lieu au nord d’Auckland. Une
        cuisine locale bistronomique est proposée aux clients avec les produits du potager. Mes
        responsabilités en tant que second de cuisine sont multiples. Je dois m’assurer que chaque section
        accomplisse son travail et que le service se déroule parfaitement. Je remplace le chef lors des ses
        repos et dirige la brigade en anglais. Une expérience riche en partage et en apprentissage dans ce
        lieu hors du temps.
        </p>
    </section>
</div>

<div class ="about__global__wrapper">
    <div class="chief__photo">
        <img src="./medias/images/chefEnAction/3.jpg" alt="photoChef">
    </div>
    <section class ="about__text__wrapper">
        <h2 class = "section__title">La rencontre du territoire calédonien</h2>
        <p>
        Au début de l’année 2020, juste avant la première vague de Covid 19, je décide de m’envoler pour la
        Nouvelle-Calédonie. Toujours équipé de ma mallette de couteaux, je décide de faire le tour du
        territoire pour découvrir ces nouveaux paysages. Je tombe amoureux de cette nature verdoyante,
        du climat tropical ensoleillé et de cette culture calédonienne qui m’est complètement inconnue. Je
        prends ensuite le poste de Chef de cuisine au restaurant Top Green Bar situé à Nouméa. Je
        développe, avec l’aide des propriétaires et de mon équipe, une cuisine fraîche, simple, mettant à
        l’honneur les produits locaux. Le succès est rapide et le restaurant a très bonne réputation dans le
        centre-ville.
        </p>
        <p>
        Mais j’ai besoin de renouveau et de plus de liberté dans ma manière d’entreprendre. C’est tout
        naturellement que je décide en mai 2021 de devenir chef à domicile. Le principe est simple, je vais
        cuisiner chez les clients pour leur faire découvrir mon univers culinaire, riche de toute mon
        expérience. Je propose une cuisine gastronomique, délicate, mettant en valeur cette diversité de
        produits calédoniens. J’aspire à ce que les clients passent un moment de partage, de générosité et
        soient surpris en découvrant des produits d’exception. Je m’entoure d’un réseau de producteurs,
        commerçants et partenaires de confiance qui partagent les mêmes valeurs que moi. En effet, la
        préservation de l’environnement écologique, social et humain est intrinsèquement liée à mon
        activité de chef à domicile. J’essaie d’intégrer au maximum cette notion dans ma cuisine en
        favorisant les circuits courts et les petits producteurs. Mes menus, rythmés par la saisonnalité, sont
        appréciés par leur fraicheur et leur finesse. La cuisine que je propose n’est que la traduction créative
        de ces magnifiques produits qui me sont offerts par le Caillou.
        </p>
    </section>
</div>

<div class ="press__global__wrapper">
    <article class ="press__article__global__wrapper">
        <h2 class = "section__title">On en parle dans la presse</h2>
        <div class="press__article__wrapper">
            <img class = "press__article" src ="./medias/presse/article1.jpg" alt="articlePresse">
            <div class ="press__article__last__page__wrapper"> 
                <img  class = "press__article" src ="./medias/presse/article2.jpg" alt="articlePresse">
                <a title="télécharger l'article" href = "./medias/presse/article.pdf" download = "Article_ChefMehdi.pdf">
                    <i class="fa-solid fa-file-arrow-down"></i>
                </a>
            </div>
        </div>
    </article>
    
    <section class ="video">
        <h2 class = "section__title">Recettes en vidéo</h2>
        <div class ="double__video__wrapper">
            <article>
                <video controls>
                    <source src ="medias/videos/avocat.webm" type ="video/webm">
                    <source src ="medias/videos/avocat.ogv" type ="video/ogg">
                    <source src ="medias/videos/avocat.mp4" type ="video/mp4">
                </video>
                <div class ="video__description__wrapper">
                    <img src="medias/images/logosVideos/logoVideoAvocat.png"></img>
                    <h3>Velouté glacé et croustillant d'avocat</h3>
                </div>
            </article>
            <article>
                <video controls>
                    <source src ="medias/videos/cafe.webm" type ="video/webm">
                    <source src ="medias/videos/cafe.ogv" type ="video/ogg">
                    <source src ="medias/videos/cafe.mp4" type ="video/mp4">
                </video>
                <div class ="video__description__wrapper">
                    <img src="medias/images/logosVideos/logoVideoCafe.png"></img>
                    <h3>Un dessert sublimé par le café du pays</h3>
                </div>
            </article>
        </div>
    </section>
</div>

    

