<h1 class ="satisfy__title">Bienvenue Chef</h1>


<div class ="user__space__global__wrapper">

    <div class ="user__space__item">
        <i class="fa-solid fa-book-open"></i>
        <a title ="modifier la carte" class ="button button__link" href= "index.php?page=update-menu">
            modifier la carte
        </a>
    </div>
    <div class ="user__space__item">
        <i class="fa-solid fa-user-pen"></i>
        <a title ="modifier mon profil" class ="button button__link" href= "index.php?page=update-user-profile">
            modifier mes infos
        </a>
    </div>

    <a href="index.php?page=disconnect" class ="logout__link"><i class="fa-solid fa-power-off"></i> Se déconnecter</a>
</div>