<section class ="confidentiality__global__wrapper">
    <h1 class ="satisfy__title">Politique de confidentialité</h1>
    <p>
     Bienvenue sur le site web du Chef à Domicile Mehdi Baileche. La protection de vos données personnelles est une priorité pour nous. Cette Politique de confidentialité vise à vous informer sur la manière dont nous collectons, utilisons, partageons et protégeons vos informations personnelles conformément au RGPD.
    </p>
    
    <h2>Collecte de données personnelles</h2>
    <p>
        Nous collectons des données personnelles lorsque vous utilisez notre site web, notamment lorsque vous remplissez un formulaire.
        Lorsque vous faites une demande de réservation, ou une demande pour offrir un bon cadeau via un formulaire, nous collectons les informations suivantes: 
    </p>
    <ul>
        <li>Votre nom</li>
        <li>Votre prénom</li>
        <li>Le nom du bénéficiaire du bon cadeau (le cas échéant)</li>
        <li>Le prénom du bénéficiaire du bon cadeau (le cas échéant)</li>
        <li>Votre email</li>
        <li>Votre numéro de téléphone</li>
        <li>Votre adresse</li>
        <li>Votre message</li>
    </ul>
    
    <h2>Utilisation des données personnelles</h2>
    <p>
        Nous utilisons vos données personnelles dans le but de répondre à vos demandes de réservation et d'améliorer notre site web et nos services.
    </p>
    
    <h2>Partage des données personnelles</h2>
    <p>
       Nous ne vendons, n'échangeons ni ne louons vos données personnelles à des tiers.
    </p>
    
    <h2>Sécurité des données</h2>
    <p>
       Nous prenons des mesures de sécurité appropriées pour protéger vos données personnelles contre la perte, l'accès non autorisé, la divulgation, la modification ou la destruction. Nous utilisons des technologies de sécurité avancées et nous mettons à jour régulièrement nos pratiques de sécurité.
    </p>
    
    <h2>Vos droits</h2>
    <p>
       Vous avez le droit de :
    </p>
    <ul>
        <li>Accéder à vos données personnelles.</li>
        <li>Rectifier vos données personnelles inexactes.</li>
        <li>Demander la suppression de vos données personnelles.</li>
        <li>Limiter le traitement de vos données personnelles.</li>
        <li>Vous opposer au traitement de vos données personnelles.</li>
    </ul>
    <p>Pour exercer vos droits ou poser des questions sur notre politique de confidentialité, veuillez nous contacter à mehdi.baileche@hotmail.fr.
    </p>
    
    <h2>Modifications de cette politique</h2>
    <p>
       Nous pouvons mettre à jour cette Politique de confidentialité de temps à autre pour refléter les changements dans nos pratiques de collecte et de gestion des données. Les modifications seront publiées sur cette page.
        Nous vous encourageons à consulter régulièrement cette Politique de confidentialité pour rester informé de nos pratiques en matière de confidentialité.
    </p>
</section>