<footer>
    <div class ="top__footer__global__wrapper">
        <div class ="contact__footer__wrapper">
            <a target= "_blank" href = "https://www.google.com/maps/place/Noum%C3%A9a+98800,+Nouvelle-Cal%C3%A9donie/@-22.2643366,166.3624651,12z/data=!3m1!4b1!4m6!3m5!1s0x6c27e2693f1a32cb:0x7bf1b22af312dd00!8m2!3d-22.2734912!4d166.4480887!16zL20vMDI1ZHpi?entry=ttu"><i class="fa-solid fa-location-dot"></i><p>Nouméa, Nouvelle-Calédonie</p>
            </a>
        </div>
        <div class ="contact__footer__wrapper">
            <a title ="téléphoner au chef" href = "tel::+687968175">
                <i class="fa-solid fa-phone"></i>
                <p>+687 968175</p>
            </a>
        </div>
        <div class ="contact__footer__wrapper">
            <a title ="envoyer un mail au chef" href = "mailto:mehdi.baileche@hotmail.fr">
                <i class="fa-solid fa-envelope"></i>
                <p>mehdi.baileche@hotmail.fr</p>
            </a>
        </div>
        <div class = "contact__footer__wrapper">
            <div class= "social__network__icons__wrapper">
                <a title ="facebook" target ="_blank" href = "https://www.facebook.com/ChefMehdiADomicile/">
                    <i class="fa-brands fa-facebook"></i>
                </a>
                <a title ="linkedin" target ="_blank" href= "https://www.linkedin.com/in/mehdi-baileche-47b45557/">
                    <i class="fa-brands fa-linkedin"></i>
                </a>
            </div>
            <p>suivre le chef sur les réseaux</p>
        </div>
    </div>
    <div class ="bottom__footer__global__wrapper">
        <div class ="large__screen__copyright">© <?= date("Y") ?></div>
        <div class ="bottom__fotter__links__wrapper">
            <a title ="mentions légales" href = "index.php?page=legal-notice">Mentions légales</a>
            <a title ="politique de confidentialité" href = "index.php?page=confidentiality">Confidentialité</a>
            <!--<a href ='index.php?page=login'><i class="fa-regular fa-user"></i></a>-->
        </div>
        <div class ="tiny__screen__copyright">© <?= date("Y") ?></div>
    </div>
</footer>
