<header>
    <div class = "header__global__wrapper">
        <div class ="mobile__header__wrapper">
            <div class ="burger__and__logo__wrapper">
                <div class ="logoDiv">
                    <img class = "logo" src="./medias/images/ChefMehdiLogo.jpg" alt="logo de chef Mehdi">
                </div>
                <div class ="burger__icon__wrapper">
                    <div class="bar first"></div>
                    <div class="bar second"></div>
                    <div class="bar third"></div>
                </div>
            </div>
        </div>
        
        <nav class ="headerNav">
            <ul>
                <li>
                    <a title ="page d'accueil" class ="nav__link" id ="home__link__desktop" href ="index.php?page=home">accueil</a>
                </li>
                    <i class="fa-solid fa-circle"></i>
                <li>
                    <a title ="à propos" class ="nav__link" id ="about__link__desktop" href ="index.php?page=about">à propos</a>
                </li>
                  <i class="fa-solid fa-circle"></i>
                <li>
                    <a title ="menus" class ="nav__link" id ="menu__link__desktop" href ="index.php?page=menu">menus</a>
                </li>
                   <i class="fa-solid fa-circle"></i>
                <li>
                    <a title ="faire un cadeau" class ="nav__link" id ="gift__link__desktop" href ="index.php?page=gift">faire un cadeau</a>
                </li>
                    <i class="fa-solid fa-circle"></i>
                <li>
                    <a title ="réserver" class ="nav__link" id ="booking__link__desktop" href ="index.php?page=booking">réserver</a>
                </li>
            </ul>
            <!--<div class ="header__nav__booking__button">-->
            <!--    <a title ="réserver" class ="button button__link" href = "index.php?page=booking">-->
            <!--       réserver une prestation-->
            <!--    </a>-->
            <!--</div>-->
        </nav>
    </div>
</header>