

<section class ="introduction">
    <div class ="home__title__wrapper">
        <h1 class ="home__title">Chef <span class ="normal__text">MEHDI</span>à domicile,</h1>
        <p>un professionnel dans votre cuisine</p>
    </div>
    <div class ="home__introduction__text__wrapper">
        <p>
        “ Chef Mehdi à domicile “ est une expérience culinaire unique. Le chef prend place dans votre
        cuisine pour vous offrir un instant gastronomique d’exception et vous faire partager sa passion des
        bons produits.
        </p>
        <p>
        Un moment hors du temps, décontracté, plein de finesse à découvrir sur Nouméa et
        ses alentours.
        </p>
    </div>
</section>

<!--CAROUSEL-->

<section class ="carousel__global__wrapper" data-speed ="7000" data-transition ="3000">
    <h2 class = "section__title galery__title">Galerie</h2>
    <div class ="elements__wrapper">
        <div class ="element active">
            <img src ="./medias/images/gallery/2.jpg" alt="photo du plat  1">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/1.jpg" alt="photo du plat  2">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/3.jpg" alt="photo du plat  3">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/4.jpg" alt="photo du plat  4">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/5.jpg" alt="photo du plat  5">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/6.jpg" alt="photo du plat  6">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/7.jpg" alt="photo du plat  7">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/8.jpg" alt="photo du plat  8">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/9.jpg" alt="photo du plat  9">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/10.jpg" alt="photo du plat 10">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/11.jpg" alt="photo du plat 11">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/12.jpg" alt="photo du plat  12">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/14.jpg" alt="photo du plat  14">
        </div>
        <div class ="element">
            <img src ="./medias/images/gallery/15.jpg" alt="photo du plat  15">
        </div>
    </div>
    <!--<i class="fa-solid fa-angle-left previous"></i>-->
    <!--<i class="fa-solid fa-angle-right next"></i>-->
    <div class ="bottom__border__carousel"></div>
</section>
<!--fin carousel-->

<div class ="home__photo__and__text__glogal__wrapper">
    <div class ="home__photo__and__text__wrapper">
        <div class ="home__photo__wrapper">
            <img src="./medias/images/chefEnAction/1.jpg" alt="photo du chef">
        </div>
        <section class ="home__text__wrapper">
            <h2 class ="section__title">Une prestation sur mesure</h2>
            <p>
            Mehdi Baileche vous transporte dans son univers culinaire pour tous types d’évènements. Faites
            appel à ses services pour un anniversaire, une rencontre entre ami(e)s, un mariage, une soirée
            d’entreprise ou bien une sortie en bateau.
            </p>
            <p>
            Le chef déplace le restaurant à l’endroit de votre choix
            afin de vous proposer une prestation culinaire correspondant à vos attentes (repas à l’assiette,
            cocktail dinatoire, brunch, buffet). Laissez-vous guider sans contrainte d’organisation, il s’occupe de
            tout et vous n’avez plus qu’à vous relaxer avec vos convives.
            </p>
        </section>
        <!--<div class="home__button__link__wrapper">-->
        <!--     <a title ="voir les menus" class ="button button__link" href ="index.php?page=menu">-->
        <!--        voir les menus-->
        <!--    </a>-->
        <!--</div>-->
    </div>
    <div class ="home__photo__and__text__wrapper" id="second__section">
        <div class ="home__photo__wrapper">
            <img src="./medias/images/chefEnAction/2.jpg" alt="photo du chef">
        </div>
        <section class ="home__text__wrapper">
            <h2 class = "section__title">Le terroir calédonien dans votre assiette</h2>
            <p>
            Une cuisine audacieuse, technique et gourmande, qui se caractérise par son attachement aux bases
            de la cuisine française, son ouverture d’esprit grâce aux inspirations de ses voyages à
            travers le monde, et son amour pour le territoire calédonien.
            </p>
            <p>
            Sa mission est de sourcer des produits
            d’exception, chez les producteurs et les fournisseurs locaux engagés, puis de les sublimer pour votre
            plaisir gustatif. Les mets élaborés par le chef sont des produits frais, de saison, favorisant les circuits
            courts calédoniens, produits en agriculture biologique ou raisonnée.
            </p>
        </section>
        <!--<div class="home__button__link__wrapper">-->
        <!--    <a title="réserver" class ="button button__link" href="index.php?page=booking">-->
        <!--        réserver une prestation-->
        <!--    </a>-->
        <!--</div>-->
    </div>
</div>

<section class ="home__advantages__global__wrapper">
    <h2 class = "section__title">Les avantages d'avoir un chef à la maison</h2>
    <div class ="home__advantages__wrapper">
        <div class ="home__advantage__wrapper">
            <i class="fa-regular fa-clock"></i>
            <h3>Simplicité d'organisation</h3>
            <p>Choisissez votre menu et le chef s'occupe du reste</p>
        </div>
        <div class ="home__advantage__wrapper">
            <i class="fa-solid fa-user-tie"></i>
            <h3>Service à table</h3>
            <p>Un service discret comme au restaurant</p>
        </div>
        <div class ="home__advantage__wrapper">
            <i class="fa-solid fa-plate-wheat"></i>
            <h3>Soirée gastronomique</h3>
            <p>Un menu raffiné d'exception</p>
        </div>
        <div class ="home__advantage__wrapper">
            <i class="fa-solid fa-hand-sparkles"></i>
            <h3>Propreté</h3>
            <p>La cuisine et la vaisselle sont propres et rangées à la fin du repas</p>
        </div>
        <div class ="home__advantage__wrapper">
            <i class="fa-solid fa-wine-glass"></i>
            <h3>Boissons</h3>
            <p>Dégustez vos boissons préférées sans droit de bouchon</p>
        </div>
    </div>
</section>

<section class ="home__partners__global__wrapper">
    <h2 class = "section__title">Les partenaires du chef</h2>
    <div class ="home__partners__wrapper">
        <a title ="la coop à nous" target ="_blank" href ="https://www.lacoopanous.nc/">
            La coop à nous
        </a>
        
        <a title ="g délices" target ="_blank" href ="https://www.facebook.com/GDelicesnoumea">
            G délices
        </a>
        
        <a title ="chez yorita" target ="_blank" href ="https://www.facebook.com/people/Chez-Yorita-Lauvray/100063507056640/?paipv=0&eav=AfbboN1SFpVVwx7IcaB93MXz9szDXU_rLWo12tO1Pe_oRjGGtt0smVS1yFodMgmg6Rg&_rdr">
            Chez Yorita
        </a>
        
        <a title ="les couteaux de vitch" target ="_blank" href ="https://www.facebook.com/vitchforge/?locale=fr_FR">
            Les couteaux de vitch
        </a>
        
        <a title ="l'atelier des alchimistes" target ="_blank" href ="https://www.facebook.com/atelier.des.alchimistes/">
            L'Atelier des Alchimistes
        </a>
        
        <a title ="maison nourry" target ="_blank" href ="https://nourry.nc/">
            Maison Nourry
        </a>
        
        <a title ="Charly's &c" target ="_blank" href ="https://www.charlysnc.com/">
            Charly's &c
        </a>
        
        <a title ="cécile collins" target ="_blank" href ="https://www.cecile-collins.com/">
            Cécile Collins
        </a>
        
        <a title ="rica" target ="_blank" href ="https://www.facebook.com/ricanouvellecaledonie/">
            RICA
        </a>
        
        <a title ="le verger de tomo" target ="_blank" href ="https://lvt-nc.shop">
            Le verger de TOMO
        </a>
    </div>
</section>

<script src="script/homeScriptCarousel.js"></script>


