<section class ="legal__notice__global__wrapper">
    <h1 class ="satisfy__title">Mentions légales</h1>  
    
    <h2>Informations générales</h2>
    
    <p>Le présent site internet est la propriété de l'entreprise de Mehdi Baileche, dont le siège social est situé au 131 Rue du 24 Septembre Haut Magenta - 98 818 Nouméa, et enregistrée sous le numéro 1497395. Vous pouvez nous contacter par e-mail à mehdi.baileche@hotmail.fr ou par téléphone au +687 968175.</p>
    
    <h2>Directeur de la publication</h2>
    
    <p>Le directeur de la publication du site internet est Mehdi Baileche.</p>
    
    <h2>Hébergeur</h2>

    <p>Le site internet est hébergé par HOSTINGER, dont le siège social est situé HOSTINGER INTERNATIONAL LTD, 61 Lordou Vironos Street, 6023 Larnaca, Chypre, joignable par le moyen suivant : <a title= "contact hébergeur" href="https://www.hostinger.fr/contact">https://www.hostinger.fr/contact.</a></p>
    
    <h2>Propriété intellectuelle</h2>
    
    <p>Tous les éléments présents sur ce site internet, y compris mais sans s'y limiter, les textes, images, vidéos, logos, sont protégés par les lois sur la propriété intellectuelle. Toute reproduction, distribution ou utilisation non autorisée de ces éléments est strictement interdite.</p>
    
    <h2>Collecte et utilisation des données personnelles</h2>
    
    <p>Nous nous engageons à respecter la vie privée de nos utilisateurs. Les données personnelles collectées par le biais de ce site internet sont utilisées uniquement dans le cadre de la prestation de services de chef à domicile et ne seront pas partagées avec des tiers sans consentement préalable.</p>
    
    <h2>Responsabilité</h2>
    
    <p>Nous nous efforçons de fournir des informations précises et à jour sur ce site internet, cependant nous ne pouvons garantir l'exactitude, l'exhaustivité ou la pertinence de ces informations. Nous déclinons toute responsabilité en cas d'utilisation inappropriée ou incorrecte des informations présentées sur ce site.</p>
    
    <h2>Liens externes</h2>
    
    <p>Ce site internet peut contenir des liens vers des sites web externes. Nous n'avons aucun contrôle sur le contenu de ces sites et déclinons toute responsabilité quant à leur contenu ou leur utilisation.</p>
    
    <h2>Mise à jour des mentions légales</h2>
    
    <p>Nous nous réservons le droit de mettre à jour ces mentions légales à tout moment. Les modifications seront publiées sur cette page et seront effectives dès leur publication.</p>
</section>