<div class ="background__wrapper">
    <div class ="background__image menu__background__image"></div>
    <div class ="background__text">
        <p class ="first__header__text">&Eacute;veillez vos papilles,</p>
        <p class ="second__header__text">LA CARTE DU CHEF</p>    
    </div>
</div>

<div class ="menu__introduction__text_wrapper">
    <p>
    Les menus à domicile comprennent un amuse-bouche, une entrée, un plat et un dessert. Vous avez
    la possibilité de rajouter un supplément fromage ainsi qu’un menu adapté pour les enfants. Le choix
    du menu doit être unique pour l’ensemble des convives (même entrée, plat et dessert). La
    prestation inclue également le service et le pain. Après avoir fait votre choix, je m’occupe du reste.
    Je fais les courses, prépare les ingrédients dans votre cuisine, sers les mets au rythme que vous
    désirez, laisse votre cuisine parfaitement propre et disparais discrètement.
    </p>
    <p>
    Le chef s’adapte à toutes sortes de demandes concernant les allergies ou autres types de
    préférences alimentaire.
    </p>
</div>

<div class ="menu__section__global__wrapper">
    <section class ="menu__wrapper">
        <h2 class ="menu__title satisfy__title">Menu Gourmet</h2>
        <div class ="large__menu__wrapper">
            <div class ="tiny__menu__wrapper">
                <img class ="menu__photo" src="./medias/images/menus/menuGourmet.jpg" alt="photo du menu gourmet">
                <div class ="tiny__menu__description__wrapper">
                    <p>&Agrave; partir de 7 800F / personne</p>
                    <p>Supplément serveur au delà de 8 personnes</p>
                    <p>Menu de saison avec des produits frais, suivant la saisonnalité. Une cuisine gourmande, raffinée avec
                    une diversité de saveurs.
                    </p>
                </div>
                <!--<a title ="voir le menu gourmet" class ="watch__menu__icon__link" href = "index.php?page=menu-gourmet">-->
                <!--    <i class="fa-solid fa-book-open-reader"></i>-->
                <!--</a>-->
            </div>
           
            <section class ="large__menu__description__wrapper">
                <h2 class ="menu__title satisfy__title">Menu Gourmet</h2>
                <p>&Agrave; partir de 7 800F / personne</p>
                <p>Supplément serveur au delà de 8 personnes</p>
                <p>Menu de saison avec des produits frais, suivant la saisonnalité. Une cuisine gourmande, raffinée avec
                une diversité de saveurs.
                </p>
                <a title="voir le menu gourmet" class= "button button__link" href = "index.php?page=menu-gourmet">
                    voir le menu
                </a>
            </section>
        </div>
        <a title="voir le menu gourmet" class= "button button__link" href = "index.php?page=menu-gourmet">
            voir le menu
        </a>
    </section>
    <section class ="menu__wrapper">
        <h2 class ="menu__title satisfy__title">Menu Prestige</h2>
        <div class ="large__menu__wrapper">
            <div class ="tiny__menu__wrapper">
                <img class ="menu__photo" src="./medias/images/menus/menuPrestige.jpg" alt="photo menu prestige">
                <div class ="tiny__menu__description__wrapper">
                    <p>&Agrave; partir de 10 800F / personne</p>
                    <p>Supplément serveur au delà de 8 personnes</p>
                    <p>Menu utilisant des produits d’exception. La noblesse des ingrédients calédoniens sublimés dans
                    votre assiette.
                    </p>
                </div>
                <!--<a title ="voir le menu prestige" class ="watch__menu__icon__link" href = "index.php?page=menu-prestige">-->
                <!--    <i class="fa-solid fa-book-open-reader"></i>-->
                <!--</a>-->
            </div>
           
            <section class ="large__menu__description__wrapper">
                <h2 class ="menu__title satisfy__title">Menu Prestige</h2>
                <p>&Agrave; partir de 10 800F / personne</p>
                <p>Supplément serveur au delà de 8 personnes</p>
                <p>Menu utilisant des produits d’exception. La noblesse des ingrédients calédoniens sublimés dans
                votre assiette.
                </p>
                <a title="voir le menu prestige" class= "button button__link" href = "index.php?page=menu-prestige">
                    voir le menu
                </a>
            </section>
        </div>
        <a title="voir le menu prestige" class= "button button__link" href = "index.php?page=menu-prestige">
            voir le menu
        </a>
    </section>
    <section class ="menu__wrapper">
        <h2 class ="menu__title satisfy__title">Cocktail dînatoire</h2>
        <div class ="large__menu__wrapper">
            <div class ="tiny__menu__wrapper">
                <img class ="menu__photo" src="./medias/images/menus/cocktail.jpg" alt="photo du menu gourmet">
                <div class ="tiny__menu__description__wrapper">
                    <p>&Agrave; partir de 4 350F / personne</p>
                    <p>(15 personnes minimum)</p>
                    <p>Supplément serveur au delà de 20 personnes</p>
                    <p>livraison possible</p>
                    <p>Un menu dinatoire comprenant des bouchées salées froides, chaudes, et sucrées. Des produits
                    locaux travaillés de manière délicate et originale sous forme de pièces dinatoires. Idéal pour les
                    réceptions entre ami(e)s ou cocktail d’entreprise.
                    </p>
                </div>
                <!--<a title ="voir le menu cocktail dînatoire" class ="watch__menu__icon__link" href = "index.php?page=cocktail-dinatoire">-->
                <!--    <i class="fa-solid fa-book-open-reader"></i>-->
                <!--</a>-->
            </div>
           
            <section class ="large__menu__description__wrapper">
                <h2 class ="menu__title satisfy__title">Cocktail dînatoire</h2>
                <p>&Agrave; partir de 4 350F / personne</p>
                <p>(15 personnes minimum)</p>
                <p>Supplément serveur au delà de 20 personnes, livraison possible</p>
                <p>Un menu dinatoire comprenant des bouchées salées froides, chaudes, et sucrées. Des produits
                locaux travaillés de manière délicate et originale sous forme de pièces dinatoires. Idéal pour les
                réceptions entre ami(e)s ou cocktail d’entreprise.
                </p>
                <a title="voir le menu cocktail dinatoire" class= "button button__link" href = "index.php?page=cocktail-dinatoire">
                    voir le menu
                </a>
            </section>
        </div>
        <a title="voir le menu cocktail dinatoire" class= "button button__link" href = "index.php?page=cocktail-dinatoire">
            voir le menu
        </a>
    </section>
</div>
<section class ="rewiews__global__wrapper">
    <h2 class = "section__title">Ils ont apprécié Chef Mehdi</h2>
    <div class ="review">
        <div class ="stars">
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
        </div>
        <p><i class="fa-solid fa-quote-left"></i>  Je vous recommande vivement Chef Mehdi, un homme généreux, discret et fort sympathique. Un professionnel, une cuisine excellente. Une présentation digne d'un grand restaurant mais à domicile. Encore merci chef, nous ne manquerons pas de vous rappeler.  <i class="fa-solid fa-quote-right"></i>
        </p>
        <p>... Bebelle Bofelio</p>
    </div>
    <div class ="review">
        <div class ="stars">
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
            <i class="fa-solid fa-star"></i>
        </div>
        <p><i class="fa-solid fa-quote-left"></i> La qualité du repas était au delà de nos espérances. Tout était parfait: les saveurs, le dressage des assiettes. Nous étions mieux qu'au restaurant ! Mehdi et Stéphane qui l'accompagnait ont été très professionnels. Ils ont tout rangé avant de repartir discrètement à la fin du repas. On ne peut que vous recommander de faire appel à Chef Mehdi. <i class="fa-solid fa-quote-right"></i>
        </p>
        <p>... Adèle Wagner</p>
    </div>
</section>
    


