<div class ="burgerNav">
    <ul class ="burgerNav__list">
        <li class ="burgerNav__list__item">
            <!--<div>-->
            <!--    <i id ="home__icon__link" class="fa-solid fa-archway burgerNav__list__item__icon"></i>-->
            <!--</div>-->
            <a title ="page d'accueil" id ="home__link" class ="burgerNav__list__item__link nav__link" href ="index.php?page=home">acceuil</a>
        </li>
        <li class ="burgerNav__list__item">
            <!--<div>-->
            <!--    <i id ="about__icon__link" class="fa-solid fa-bread-slice burgerNav__list__item__icon"></i>-->
            <!--</div>-->
            <a title ="à propos" id ="about__link" class ="burgerNav__list__item__link nav__link" href ="index.php?page=about">à propos </a>
        </li>
        <li class ="burgerNav__list__item">
            <!--<div>-->
            <!--    <i id ="menu__icon__link" class="fa-solid fa-book-open burgerNav__list__item__icon"></i>-->
            <!--</div>-->
            <a title ="menus" id ="menu__link" class ="burgerNav__list__item__link nav__link" href ="index.php?page=menu">menus</a>
        </li>
        <li class ="burgerNav__list__item">
            <!--<div>-->
            <!--    <i id ="gift__icon__link" class="fa-solid fa-gift burgerNav__list__item__icon"></i>-->
            <!--</div>-->
            <a title ="faire un cadeau" id ="gift__link" class ="burgerNav__list__item__link nav__link" href ="index.php?page=gift">faire un cadeau</a>
        </li>
        <li class ="burgerNav__list__item">
            <!--<div>-->
            <!--    <i id ="gift__icon__link" class="fa-solid fa-utensils burgerNav__list__item__icon"></i>-->
            <!--</div>-->
            <a title ="réserver" id ="booking__link" class ="burgerNav__list__item__link nav__link" href ="index.php?page=booking">Réserver</a>
            <!--<a class ="button booking__burger__nav__button burgerNav__list__item__link" href = "index.php?page=booking">-->
            <!--   réserver une prestation-->
            <!--</a>-->
        </li>
    </ul>
</div>