<h1 class ="satisfy__title">Mot de passe oublié</h1>

<p class ="form__text">Renseignez l'email de votre compte pour recevoir un nouveau mot de passe</p>

<form id ="new__password__form" class= "form new__password__form" method="POST" novalidate>
    <?php
    //affichage d'une info bulle si l'email n'est pas dans la base de données
    if($data['formScore'] == 1) {
        echo "<div class ='info__bulle__header__form display__info__bulle'>
            cet email n'est associé à aucun compte 
        </div>";
    }
    ?>
    <div class ="form__double__input__wrapper">
        <div class ="form__input__wrapper">
            <label class ="form__label" for="email__newpass">Email</label>
            <input class ="form__input" id = "email__newpass" type="email" name="email" required autocomplete ="email">
            <div class ="info__bulle__form email__info"></div>
        </div>
       
    </div>
    <button class ="button" type ="submit" name="newPassword">envoyer</button>
</form>