<!doctype html>

<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name = "viewport" content = "width=device-width, initial-scale=1.0">
        <title><?= $data ["title"] ?></title>
        
        <!--lien pour éviter une erreur favicon.ico 404 à la lecture de la video-->
        <link rel="shortcut icon" href="#">
        
        <!--lien pour les icones-->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer">
        
        <!--liens pour le fichier css-->
        <link rel="stylesheet" href="css/style.css" type="text/css" >

        <!--lien ajax-->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" defer></script>
        <!--lien javascript global-->
        <script src="./script/script.js" defer></script>
        
       
        <!--autres script-->
        
    </head>
    <body>
        
        <?php require_once "header.phtml"; ?>
        <?php require_once "nav.phtml"; ?>
        
        <main>
            <?php
                if (isset($view)) {
                    require_once $view;
                }
            ?>
        </main>
        <?php require_once "footer.phtml"; ?>
        <a href="#" class ="to__top">
            <i class="fa-solid fa-angle-up"></i>
        </a>
    </body>
</html>